"""initial migration

Revision ID: 4506123d2c80
Revises: None
Create Date: 2015-07-14 00:00:17.800973

"""

# revision identifiers, used by Alembic.
revision = '4506123d2c80'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
